### ISSUE TITLE
Is there possibility to change WSAD inputs to arrow keys?

### ISSUE THREAD

**Issue by PatrykBiernacki** [spyoungtech/helldivers2-macros#13]
Sorry to bother, i love your work. 
As written in title, is there possibility to change WSAD inputs to arrow keys?
Thank you.

**Comment by spyoungtech** [comment]
Technically, yes. The mapping is [declared here](https://github.com/spyoungtech/helldivers2-macros/blob/fc5427b1c0fcae853301769bb040ad07e5d99d8c/hd2_macros/constants.py#L123) and this _could_ be changed to use arrow keys instead of WASD if you're using the Python variant of the application -- however it's not user-configurable in the `config.toml` file and probably not terribly easy to modify if you're using the compiled version of the program.

I'll see if I can make this a configurable feature in the config file.

**Comment by PatrykBiernacki** [comment]
Thats great! Thank you. On higher difficulties moving while using stratagem can be a lifesaver.

**Comment by spyoungtech** [comment]
@PatrykBiernacki I've added this to the latest release. As noted now in the readme, you can configure use of arrow keys instead of WASD now.

In the `config.toml`, just add the following under the `[general]` section:

```toml
input_type = "Arrows"
```

I haven't tested this, so let me know if it works for you or not.
